### ISSUE TITLE
case of lost data in Compendium 1.5

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#109]
import from mail-list on 2013-Jan-5 by MarioG

I am looking to map A opened, viewing maps B, C and D. B has two
arrows coming from C and D. B contains C and D, so each of C and D has
a transclusion count of 2.
Now the fun: I made map B into a node (alt-shift-m) because I no
longer needed maps C and D inside. As I am warned about nodes into B
being deleted if they are not transcluded elsewhere, I say yes.
Surprise? All nodes in C and D disappear, so that maps C and D, which
were transcluded in A and connected to B, are empty.
So for the probably fifth time in four months I'm using Compendium, I
lost my data. Maps C and D required half a day of work and had many
nodes inside (more than 100), all of which has disappeared, except
from some which were transcluded to other views.
Compendium is as awesome as buggy. I'm trying to restore from my "real
time" backup which runs every 15 minutes.

**Comment by maiklos** [comment]
I want to try reproduce this behavior on CompendiumNG.
If the fix is not complex then, we might consider to (exceptionally) submit patch also for 1.5.3 so users who are stuck on 1.5 version are not at risk of loosing data.

**Comment by maiklos** [comment]
tested on Sun Java 6 / Linux gentoo

I have managed to reproduce the problem with following extra observation.

after you change the map B to a node change it back to map and the map will have C and D maps however they are just fragments. if you click on one of them you will get an exception because it already doesn't exist. You can delete them though.

otherwise the bug is as the reported stated with exception that other nodes in map C & D are still visible there but obviously corrupted because after clicking them you receive various exceptions:

<pre>
20130105 21:06:01,359+0100 ERROR [AWT-EventQueue-0] (UIMapViewFrame.java:929) viewframe not selected because 
java.lang.ArrayIndexOutOfBoundsException: 30 >= 24
    at java.util.Vector.elementAt(Vector.java:427)
    at com.compendium.ui.UIHistory.add(UIHistory.java:93)
    at com.compendium.ui.toolbars.UIToolBarMain.addToHistory(UIToolBarMain.java:576)
    at com.compendium.ui.toolbars.UIToolBarManager.addToHistory(UIToolBarManager.java:1185)
    at com.compendium.ui.ProjectCompendiumFrame.activateWindow(ProjectCompendiumFrame.java:6300)
    at com.compendium.ui.UIViewFrame.internalFrameActivated(UIViewFrame.java:450)
    at javax.swing.JInternalFrame.fireInternalFrameEvent(JInternalFrame.java:1561)
    at javax.swing.JInternalFrame.setSelected(JInternalFrame.java:1102)
    at com.compendium.ui.UIMapViewFrame.setSelected(UIMapViewFrame.java:926)
    at javax.swing.JInternalFrame.show(JInternalFrame.java:1739)
    at java.awt.Component.show(Component.java:1591)
    at java.awt.Component.setVisible(Component.java:1543)
    at javax.swing.JComponent.setVisible(JComponent.java:2620)
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:6004)
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:5786)
    at com.compendium.ui.plaf.NodeUI.openNode(NodeUI.java:2277)
    at com.compendium.ui.plaf.NodeUI.mouseClicked(NodeUI.java:2237)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:253)
    at java.awt.Component.processMouseEvent(Component.java:6300)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6062)
    at java.awt.Container.processEvent(Container.java:2039)
    at java.awt.Component.dispatchEventImpl(Component.java:4660)
    at java.awt.Container.dispatchEventImpl(Container.java:2097)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4245)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
    at java.awt.Container.dispatchEventImpl(Container.java:2083)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:668)
    at java.awt.EventQueue.access$400(EventQueue.java:81)
    at java.awt.EventQueue$2.run(EventQueue.java:627)
    at java.awt.EventQueue$2.run(EventQueue.java:625)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:641)
    at java.awt.EventQueue$3.run(EventQueue.java:639)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:638)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
</pre>

or

<pre>
20130105 21:06:11,459+0100 ERROR [AWT-EventQueue-0] (NodeUI.java:2396) Exception...
java.util.NoSuchElementException: Node with id 10001021357416191127 could not be found in this view
    at com.compendium.core.datamodel.View.setNodePosition(View.java:1590)
    at com.compendium.ui.plaf.NodeUI.mouseReleased(NodeUI.java:2393)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:273)
    at java.awt.Component.processMouseEvent(Component.java:6297)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6062)
    at java.awt.Container.processEvent(Container.java:2039)
    at java.awt.Component.dispatchEventImpl(Component.java:4660)
    at java.awt.Container.dispatchEventImpl(Container.java:2097)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
    at java.awt.Container.dispatchEventImpl(Container.java:2083)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:668)
    at java.awt.EventQueue.access$400(EventQueue.java:81)
    at java.awt.EventQueue$2.run(EventQueue.java:627)
    at java.awt.EventQueue$2.run(EventQueue.java:625)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:641)
    at java.awt.EventQueue$3.run(EventQueue.java:639)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:638)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
</pre>
