### ISSUE TITLE
NullPointerException at org.compendiumng.tools.Utilities.GetImageIcon(Utilities.java:131) with 64-bit OpenJDK 7 on Debian jessie/sid

### ISSUE THREAD

**Issue by aleksejrs** [CompendiumNG/CompendiumNG#208]
Built branch 2.1.3 (commit dc4fa65db9b58437eb5a63a59c223c3f8a7f60ba).

$ java -showversion
java version "1.7.0_21"
OpenJDK Runtime Environment (IcedTea 2.3.9) (7u21-2.3.9-5)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

```
~/CompendiumNG$ java -jar CompendiumNG.jar 
19:24:04.229 [main] INFO  com.compendium.ProjectCompendium - Starting CompendiumNG version 2.1.3
19:24:04.242 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=compendiumng.config.dir) -> *** UNDEFINED ***
19:24:04.242 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.version) -> 1.7.0_21
19:24:04.243 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.vm.version) -> 23.7-b01
19:24:04.243 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.runtime.version) -> 1.7.0_21-b02
19:24:04.244 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.vendor) -> Oracle Corporation
19:24:04.244 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=sun.boot.class.path) -> /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/netx.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/plugin.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rhino.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/classes
19:24:04.244 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.ext.dirs) -> /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
19:24:04.244 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.vm.info) -> mixed mode
19:24:04.245 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=sun.java.command) -> CompendiumNG.jar
19:24:04.245 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.class.path) -> CompendiumNG.jar
19:24:04.245 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=user.timezone) -> Europe/Moscow
19:24:04.246 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=user.home) -> /home/.dec/mm
19:24:04.246 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=os.name) -> Linux
19:24:04.246 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=os.version) -> 3.10-3-amd64
19:24:04.246 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.library.path) -> /usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
19:24:04.247 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.io.tmpdir) -> /tmp
19:24:04.248 [main] INFO  com.compendium.ProjectCompendium - java.properties(key=java.vm.name) -> OpenJDK 64-Bit Server VM
19:24:04.255 [main] INFO  com.compendium.ProjectCompendium - application base directory: /home/.dec/mm/CompendiumNG/
19:24:04.257 [main] INFO  com.compendium.ProjectCompendium - found configuration directory /home/.dec/mm/compendiumng_config 
19:24:04.258 [main] INFO  com.compendium.ProjectCompendium - user settings directory: /home/.dec/mm/compendiumng_config/
19:24:04.259 [main] INFO  com.compendium.ProjectCompendium - dir.data is not explicitly set from command line... deriving own value...
19:24:04.259 [main] INFO  com.compendium.ProjectCompendium - user data directory: /home/.dec/mm/CompendiumNG/data/
19:24:04.260 [main] DEBUG com.compendium.ProjectCompendium - configuration file /home/.dec/mm/compendiumng_config/main.properties already exists... loading
19:24:04.277 [main] DEBUG o.a.c.c.PropertiesConfiguration - Base path set to file:///home/.dec/mm/compendiumng_config/main.properties
19:24:04.292 [main] DEBUG o.a.c.c.PropertiesConfiguration - FileName set to main.properties
19:24:04.292 [main] DEBUG o.a.c.c.PropertiesConfiguration - Base path set to /home/.dec/mm/compendiumng_config
19:24:04.293 [main] INFO  com.compendium.ProjectCompendium - saving configuration: /home/.dec/mm/compendiumng_config/main.properties
19:24:04.398 [main] INFO  com.compendium.ProjectCompendium - Internet search allowed due to configuration option. URL = http://www.google.com/search?hl=en&lr=&ie=UTF-8&oe=UTF-8&q=
19:24:04.399 [main] INFO  com.compendium.ProjectCompendium - checking necessary directories...
19:24:04.400 [main] INFO  com.compendium.ProjectCompendium - checking: /home/.dec/mm/CompendiumNG/data/
19:24:04.401 [main] INFO  com.compendium.ProjectCompendium - checking: /home/.dec/mm/CompendiumNG/data/Backups/
19:24:04.402 [main] INFO  com.compendium.ProjectCompendium - checking: /home/.dec/mm/CompendiumNG/data/Exports/
19:24:04.403 [main] INFO  com.compendium.ProjectCompendium - checking: /home/.dec/mm/CompendiumNG/ProjectTemplates/
19:24:04.404 [main] INFO  com.compendium.ProjectCompendium - checking: /home/.dec/mm/CompendiumNG/data/LinkedFiles/
19:24:04.406 [main] INFO  com.compendium.ProjectCompendium - checking: /home/.dec/mm/CompendiumNG/Templates/
19:24:04.414 [main] INFO  com.compendium.LanguageProperties - Loading non-default locale (en_US) specified in the configuration file
19:24:05.297 [main] DEBUG org.compendiumng.tools.Utilities - ImageIconCache miss on: /home/.dec/mm/CompendiumNG/images/broken-image.png
Exception in thread "main" java.lang.NullPointerException
    at org.compendiumng.tools.Utilities.GetImageIcon(Utilities.java:131)
    at com.compendium.ui.dialogs.UIStartUp.<init>(UIStartUp.java:87)
    at com.compendium.ProjectCompendium.main(ProjectCompendium.java:348)
```

**Comment by maiklos** [comment]
this seems to me like openjdk related problem

**Comment by maiklos** [comment]
could you please check if you have following file: /home/.dec/mm/CompendiumNG/images/broken-image.png ?

**Comment by aleksejrs** [comment]
Yes, a 32x32 icon.

**Comment by maiklos** [comment]
when parameter system.splash.image is missing in you configuration file (main.cfg) then this problem occurs. I have committed the fix for it. However I think there is something wrong with your installation since configuration file should have it after the installation.

**Comment by maiklos** [comment]
closing this issue. If it still persist we will reopen it later.

**Comment by aleksejrs** [comment]
I have general computer issues, will probably be back in a few weeks.
