### ISSUE TITLE
Images are not correctly displayed on stencils and reference nodes

### ISSUE THREAD

**Issue by ClearBlueSky85** [CompendiumNG/CompendiumNG#217]
I think that there has been some changes in the installation and file directory structure which was due to the desire to separate user data from the program installation data.  However I think that there are some instances in the code where locations have been statically hard-coded in and have not been updated.  I am not sure whether or not the code has been tested on a clean installation on all different operating systems which uses the current directory structure that is provided in the resources directory, since it seems apparent to me that some of the basic functionality of the program seems to be broken.  Personally I think that there should be a better method of configuring and calling the absolute paths to the different directories that the program uses, and that the user should be able to customize the directories with an advanced installation dialog or modifying an advanced configuration file.  Having one single global list of file system directories and locations would help by reducing confusion, for example, having to remember whether or not you have put the file system separator at the end of a string that was previously named in a separate script.

**Reference Node Icons are not displayed**

I am not able to see reference node icons when I reference a file with a known file extension.  The XMLReader is able to load the [referencenodetypes.xml](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/resources/images/ReferenceNodeIcons/referencenodetypes.xml).  However I believe that the path to the reference node icons themselves has not been updated.  

In [UIImages](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/com/compendium/ui/UIImages.java) script the sREFERENCEPATH variable for the reference node images is statically set to "DIR_BASE\ReferenceNodeIcons" however it should be set to ["DIR_BASE\images\ReferenceNodeIcons"](https://github.com/CompendiumNG/CompendiumNG/tree/2.1.4/application/src/main/resources/images/ReferenceNodeIcons) instead.  In [UIReferenceNodeManager](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/com/compendium/ui/UIReferenceNodeManager.java) the sFILEPATH variable for the reference node image XML configuration file is correctly set to "DIR_BASE\images\ReferenceNodeIcons".  However this sFILEPATH variable is not the same variable that is used by the [UIImages](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/com/compendium/ui/UIImages.java) script.  When I manually copy the "DIR_BASE\images\ReferenceNodeIcons" to a new directory "DIR_BASE\ReferenceNodeIcons" I am able to see the reference node icons, so  I can confirm that this is the issue.

Just as a suggestion, maybe you need to have a global configuration settings file that each separate script can reference, so that every script will all be referencing the same location.

This is related to the following issue:  [Reference Files Icons are not correctly displayed #177](https://github.com/CompendiumNG/CompendiumNG/issues/177)

**Stencil Icons are not displayed**

I am not able to see the stencil icons in my maps.  I am able to see the stencil icons in the stencil manager as well as in the stencil palette after loading a stencil set.  However when I drag and drop a stencil into a map, all that is displayed is the broken image icon. I looked at the log file at the point when I tried to add a new node from a stencil and it shows only the relative path (e.g. STENCIL_NAME\nodeimages\node1.png), which does not seem correct because it does not include the full absolute path like all of the other ImageIconCache entries in the log file.  I tried to do some research on some of the other log entries, however since I am not familiar with Java, I am not sure how to fix it.

After reviewing my log file, it looks like the [UIStencilManager](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/com/compendium/ui/stencils/UIStencilManager.java) finds all of my stencils and tries to load all of the stencil images, however the [Utilities](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/org/compendiumng/tools/Utilities.java) script reports an ImageIconCache "miss" for all of the stencil images that it tries to load.  It also reports "miss" for some icons listed, but then will report "hit" for the same file sometime later on in the log file.  I have looked at the [Utilities](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/org/compendiumng/tools/Utilities.java) script and am not sure what ImageIconCache "miss" means.  

I looked at the [ProjectCompendium](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/com/compendium/ProjectCompendium.java) script and it seems inconsistent to me whether or not the file system separator is added to the end of the directory strings.  For example the DIR_IMAGES string has a file separator between the base directory and the images subfolder, however the DIR_STENCILS string does not include a file separator between the base directory and the stencils subfolder.  It might be helpful to add a feature to write all of the user and application resource directory strings (e.g. DIR_SKINS, DIR_IMAGES, DIR_STENCILS, DIR_REFERENCE_NODE_ICONS, etc.) to the log file as well.  

I looked at the [UIImages](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/com/compendium/ui/UIImages.java) script and I could not find any mention of the stencils directories.  I am not sure how the application knows to load the stencil images.  I would suggest as an improvement that when loading the image icons, that the program searches different locations for the icons in an order of precedence.  For example, say that there is a node that has a relative path STENCIL_NAME\nodeimages\node1.png, then the program could first look in DIR_IMAGES, DIR_STENCILS, or DIR_LINKED_FILES.  Or as an alternative implementation, the program could check to see if the prefix of the relative path matches a known stencil set, and then know to look for the stencil images in that particular stencil directory, rather than the images directory.  

All of my stencil sets have a relative path listed in their configuration file.  I think that I could fix this issue if I went in and changed all of my stencils XML configuration files to have absolute paths listed, instead of relative paths based on the stencil directory.  However I don't think that this would be an ideal solution.  I think that having relative paths are important, for example when creating stencil sets that are to be used on different systems with different installation directories.  

In general I think that there may be issues with the program calling and/or receiving either absolute or relative paths, and that some absolute paths are inconsistently referenced and hard-coded into the code.

**Comment by maiklos** [comment]
for reference node icons not displaying I've reopened issue #177

**Comment by maiklos** [comment]
a note regarding miss/hit message:
cng is newly using cache for images. First time when some image is used it is not able to load it from cache so you will see "miss" message and it tries to load the image into cache and return it. Next time the same image is use you should see "hit" message since the image is already loaded in cache (memory).

**Comment by maiklos** [comment]
now as for branch 2.1.5 it prints out used directories in the log file during startup

**Comment by ClearBlueSky85** [comment]
Ok thanks for adding the extra startup log entries.  

I think to get the reference icons to work you need to change [UIImages](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ui/UIImages.java) line 72 so that sREFERENCEPATH is set to the correct directory:
UIImages line 72 was:

``` java
private final static String sREFERENCEPATH = ProjectCompendium.DIR_BASE + File.separator + sFS + "ReferenceNodeIcons" + sFS; //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
```

UIImages line 72 now:

``` java
private final static String sREFERENCEPATH = ProjectCompendium.DIR_IMAGES + File.separator + "ReferenceNodeIcons" + File.separator; //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
```

Note that UIImages line 72 previous referenced the base directory, however the reference node icons are currently under the images directory here:  [ReferenceNodeIcons](https://github.com/CompendiumNG/CompendiumNG/tree/2.1.5/application/src/main/resources/images/ReferenceNodeIcons)

Then the reference node icon directory will be the same as [UIReferenceNodeManager](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ui/UIReferenceNodeManager.java) line 61
UIReferenceNodeManager line 61:

``` java
public final static String sFILEPATH = ProjectCompendium.DIR_IMAGES + File.separator +"ReferenceNodeIcons" + File.separator + "referencenodetypes.xml"; //$NON-NLS-1$
```

PS I think that previously UIImages line 72 had an extra file separator and I am not sure why that was there

PPS I am not sure why these No National Language Support //$NON-NLS-1$ flags are added after these lines to suppress warnings (see [What does $NON-NLS-1$ mean?](http://stackoverflow.com/questions/654037/what-does-non-nls-1-mean) and [What does the number after //$NON-NLS- mean](http://stackoverflow.com/questions/18087687/what-does-the-number-after-non-nls-mean) )

There might be a better way to implement the reference icon fix, this is just a suggestion.

Thanks

**Comment by maiklos** [comment]
using of DIR_XXX directories is the new way that honours separation of application, settings and user data. Still there are places in the code where old way is surviving. Also DIR_xxx are partially derived or calculated during startup to support portable mode. I've made minor modification so stencils and reference node icons can be used again. Please test it. (as for stencils I suspect that map with stencils is not portable to another installation or machine. 1) because image is recorded with absolute path 2) your own crafted stencils are not available on other installation)

$NON-NLS-x is used for translations. When using automatic tool for extracting all string from the code then NON-NLS-x marked strings are ignored. number (x) is position of a string that this "ignore" rule applies to. It mostly used for String that are not locale specific.

**Comment by ClearBlueSky85** [comment]
Ok I tested the reference icon issue and believe that the reference node icons are now displayed correctly, although I had a couple of minor comments regarding reference node icons that I posted under [Issue #177](https://github.com/CompendiumNG/CompendiumNG/issues/177).

I did find some places in the code where the old way of calling the stencil directory is still surviving:
[DBBackupDatabase](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/core/db/management/DBBackupDatabase.java) Line 388
[PrefuseGraphXMLExport](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/io/xml/PrefuseGraphXMLExport.java) Line 430 & 431
[XMLExport](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/io/xml/XMLExport.java) Line 663 & 664
[XMLExportNoThread](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/io/xml/XMLExportNoThread.java) Line 652 & 653

Regarding comment (1) above, I do not think that stencils are recorded with absolute path by stencil XML configuration file.  For example look at the [De_Bono_6_Hats_Thinking.xml](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/resources/Stencils/De_Bono_6_Hats_Thinking/De_Bono_6_Hats_Thinking.xml) Line 35 where the node image is specified by file name only `image="black.hat.jpg"`.  I think that the [UIStencilManager](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ui/stencils/UIStencilManager.java) loadStencils() routine starting on line 290, it loads the stencil XML configuration file and then calls some other routines that figure out where the images are located.  It's hard for me to follow the code since it references a lot of different scripts and I can't really tell which routine is loading the stencil images into the image cache.  I think that it might be the [UIStencilManager](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ui/stencils/UIStencilManager.java) createStencil() routine starting on line 400.  On line 424 the stencil node image path is constructed `sImage = sFolderName+sFS+UIStencilSet.sNODEIMAGEDIR+sFS+sImage;`.  Then there are a lot of other references to [Utilities](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/org/compendiumng/tools/Utilities.java), [UIImages](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ui/UIImages.java), and [DraggableStencilIcon](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ui/stencils/DraggableStencilIcon.java) where the node image location gets appended to the base stencil directory in [Utilities](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/org/compendiumng/tools/Utilities.java) GetImageIcon(image_name, base_path).  This is where I am seeing in my log file instances where it says "ImageIconCache miss".  Then all I am seeing when I try to add a stencil node is the broken image.

Is there possibly a way to export or write to file the ImageIconCache to see if the stencil icons actually get loaded into cache or if the missing image icon gets loaded into cache instead?  Maybe add an extra log file entry on Utilities line 165 just in case exception isn't being written to log file?  

Thanks

**Comment by jeroen69** [comment]
This is still a problem, or again. 

![screen shot 2016-03-23 at 10 32 37 am](https://cloud.githubusercontent.com/assets/3942502/13992678/a26514ce-f0e2-11e5-8caf-d59eda245bec.png)

**Comment by maiklos** [comment]
Could you please:
1) shut down compendium
2) delete log files (or put them aside)
3) start compendium and replicate the bug
4) shutdown compendium
5) provide us the new log file
?

Also please provide brief information about your system (Mac,Linux,Win? - which version)
Thanks

**Comment by jeroen69** [comment]
Thank you for the response!

I Am using CompendiumNG 2.1.4 on a MacBook Pro with OS X 10.11.3

I started compendium, opened the stencil set I made, one image showed up this morning
![screen shot 2016-03-25 at 8 47 50 am](https://cloud.githubusercontent.com/assets/3942502/14046553/ddfd95d4-f267-11e5-8ef1-9f9c847046aa.png)

Dragged one of the broken images to the map. 
![screen shot 2016-03-25 at 8 48 32 am](https://cloud.githubusercontent.com/assets/3942502/14046566/ee208d4a-f267-11e5-9fcb-68f906e706aa.png)

Here's the log file. 

[compendiumng.txt](https://github.com/CompendiumNG/CompendiumNG/files/189633/compendiumng.txt)

I notice that the application is installed in Applications and the log file is stored in my home folder. 

Let me know if there's any other questions or comments!

Best wishes, 
Jeroen

**Comment by maiklos** [comment]
Thank you for the log. However it looks incomplete. However:

I see miss and hit for ID_Target.png file

<pre>
2016-03-25 08:47:58,228 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:156 ImageIconCache miss on: Instructional_Design_elements/nodeimages/Instructional_Design_elements/nodeimages/Instructional_Design_elements/nodeimages/ID_Target.png
2016-03-25 08:47:58,327 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:245 mod(⇧[1]) wheel: -1 current zoom: 1.0
2016-03-25 08:48:44,347 DEBUG [NodeUI: EditDialog] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: Instructional_Design_elements/nodeimages/Instructional_Design_elements/nodeimages/Instructional_Design_elements/nodeimages/ID_Target.png
</pre>

later there is an exception

<pre>
2016-03-25 08:49:07,332 ERROR [AWT-EventQueue-0] c.c.u.ExecuteControl ExecuteControl.java:100 Exception...
java.lang.IllegalArgumentException: The file: Instructional_Design_elements/nodeimages/Instructional_Design_elements/nodeimages/Instructional_Design_elements/nodeimages/ID_Target.png doesn't exist.
    at java.awt.Desktop.checkFileValidation(Desktop.java:210) ~[na:1.8.0_73]
    at java.awt.Desktop.open(Desktop.java:270) ~[na:1.8.0_73]
    at com.compendium.ui.ExecuteControl.launchFile(ExecuteControl.java:132) ~[CompendiumNG.jar:2.1.4-SNAPSHOT]
...
</pre>

however I am not sure if this is related to your problem.

I don't have any idea where "Instructional_Design_elements" stencils come from. They are not in current standard installation of CompendiumNG. Unluckily only relative path is logged so I am not sure if it is part of you map or where exactly are the expected to be.

I suspect that the map was created on earlier version of Compendium and later opened in current version of CompendiumNG. Also I think that "Instructional_Design_elements" are part of custom created stencil set and they are missing in your installation now... could it be the case ?

Please check icon/image path of the node which doesn't have the icon displayed (Business need) - from node dialog.

I will try to add some more details into log.
Also please check why was the log file cut/shortened.

Thanks
maiklo

**Comment by jeroen69** [comment]
Sorry about the confusion, yes I created custom stencils. Perhaps that is a second issue - not being able to create stencils. 

I have attached a new log. This time adding the included bono thinking hats black hat stencil. Adding it to the map looks like this: 
![screen shot 2016-03-28 at 8 27 24 am](https://cloud.githubusercontent.com/assets/3942502/14080040/a347b370-f4bf-11e5-8f3b-53442e2810af.png)

Content of the node looks like this: 
![screen shot 2016-03-28 at 8 28 07 am](https://cloud.githubusercontent.com/assets/3942502/14080049/b4ccafa6-f4bf-11e5-89d8-859af76827d4.png)

When I click browse to search for the image, the browse window takes me to my Home directory (where the Compendium log is also stored). I then have to browse to the higher level application folder where Compendium was installed and search for the stencil image here: 
![screen shot 2016-03-28 at 8 29 00 am](https://cloud.githubusercontent.com/assets/3942502/14080087/fd2eb500-f4bf-11e5-90b4-ee7d9a111c6d.png)

After selecting this the black hat image appears to stay visible in the map: 
<img width="180" alt="screen shot 2016-03-28 at 8 29 42 am" src="https://cloud.githubusercontent.com/assets/3942502/14080097/0cadf3e2-f4c0-11e5-93ce-d6e5a82b5521.png">

Attached the log file: 
[compendiumng.txt](https://github.com/CompendiumNG/CompendiumNG/files/191909/compendiumng.txt)

Thanks for looking into this!
Cheers, Jeroen
