### ISSUE TITLE
Export Web Outline not working

### ISSUE THREAD

**Issue by nalbarel** [CompendiumNG/CompendiumNG#218]
When trying to export a Web Outline I get exceptions.
File --> Export --> Web Outline throws Exception: (UIExportDialog.reloadData) null
Then in the export tool, I do not have any 'Default' Outline format and I am not able to save one.
I am under Win7 and working on version 2.1.4. I do not have any OutlineConfig folder on my machine.

**Comment by maiklos** [comment]
thanks for reporting this.
this error is easy reproducible. related stack trace from the log:

``` javastack
2014-04-15 19:57:44,278 ERROR [AWT-EventQueue-0] c.c.u.d.UIExportDialog UIExportDialog.java:1288 Exception...
java.lang.NullPointerException: null
        at com.compendium.ui.dialogs.UIExportDialog.reloadData(UIExportDialog.java:1259) [CompendiumNG.jar:2.1.4-SNAPSHOT]
        at com.compendium.ui.dialogs.UIExportDialog.createStylesChoiceBox(UIExportDialog.java:1203) [CompendiumNG.jar:2.1.4-SNAPSHOT]
        at com.compendium.ui.dialogs.UIExportDialog.createOptionsPanel(UIExportDialog.java:995) [CompendiumNG.jar:2.1.4-SNAPSHOT]
        at com.compendium.ui.dialogs.UIExportDialog.<init>(UIExportDialog.java:405) [CompendiumNG.jar:2.1.4-SNAPSHOT]
        at com.compendium.ui.ProjectCompendiumFrame.onFileExportHTMLOutline(ProjectCompendiumFrame.java:2727) [CompendiumNG.jar:2.1.4-SNAPSHOT]
        at com.compendium.ui.menus.UIMenuFile.actionPerformed(UIMenuFile.java:525) [CompendiumNG.jar:2.1.4-SNAPSHOT]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018) [na:1.7.0_51]
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341) [na:1.7.0_51]
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.7.0_51]
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [na:1.7.0_51]
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376) [na:1.7.0_51]
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833) [na:1.7.0_51]
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877) [na:1.7.0_51]
        at java.awt.Component.processMouseEvent(Component.java:6505) [na:1.7.0_51]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3320) [na:1.7.0_51]
        at java.awt.Component.processEvent(Component.java:6270) [na:1.7.0_51]
        at java.awt.Container.processEvent(Container.java:2229) [na:1.7.0_51]
        at java.awt.Component.dispatchEventImpl(Component.java:4861) [na:1.7.0_51]
        at java.awt.Container.dispatchEventImpl(Container.java:2287) [na:1.7.0_51]
        at java.awt.Component.dispatchEvent(Component.java:4687) [na:1.7.0_51]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832) [na:1.7.0_51]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492) [na:1.7.0_51]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422) [na:1.7.0_51]
        at java.awt.Container.dispatchEventImpl(Container.java:2273) [na:1.7.0_51]
        at java.awt.Window.dispatchEventImpl(Window.java:2719) [na:1.7.0_51]
        at java.awt.Component.dispatchEvent(Component.java:4687) [na:1.7.0_51]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735) [na:1.7.0_51]
        at java.awt.EventQueue.access$200(EventQueue.java:103) [na:1.7.0_51]
        at java.awt.EventQueue$3.run(EventQueue.java:694) [na:1.7.0_51]
        at java.awt.EventQueue$3.run(EventQueue.java:692) [na:1.7.0_51]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_51]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_51]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87) [na:1.7.0_51]
        at java.awt.EventQueue$4.run(EventQueue.java:708) [na:1.7.0_51]
        at java.awt.EventQueue$4.run(EventQueue.java:706) [na:1.7.0_51]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_51]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_51]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:705) [na:1.7.0_51]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_51]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_51]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_51]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_51]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_51]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_51]
2014-04-15 19:57:44,279 INFO  [AWT-EventQueue-0] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6064 Error:Exception: (UIExportDialog.reloadData) null
```

**Comment by maiklos** [comment]
1) Default.properties and OutlineStyles dir are missing
2) if it is missing then NullPointer exception happens and not meaningful error is displayed/logged
