### ISSUE TITLE
Drag and drop not working on Windows 7

### ISSUE THREAD

**Issue by laurarhian** [CompendiumNG/CompendiumNG#225]
As in the title bar- I'm on Windows 7, can't drag and drop files onto a map to create reference nodes.  Adding nodes manually works.  

Drag and drop works in other programs.

**Comment by maiklos** [comment]
may I ask you to run cng logging in debug mode and provide the log file ?

**Comment by laurarhian** [comment]
Certainly, how do I do that in windows?

**Comment by laurarhian** [comment]
Think I've found it, is the below of use?

<pre>
2014-06-19 10:59:24,989 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 14 path: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:24,990 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:156 ImageIconCache miss on: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:25,003 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 14 path: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:25,004 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:25,004 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 14 path: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:25,005 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:25,006 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 14 path: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:25,006 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Apps\Compendium\Skins\Default\note.png
2014-06-19 10:59:25,007 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 13 path: C:\Apps\Compendium\Skins\Default\reference.png
2014-06-19 10:59:25,007 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:156 ImageIconCache miss on: C:\Apps\Compendium\Skins\Default\reference.png
2014-06-19 10:59:25,014 INFO  [AWT-EventQueue-0] c.c.u.UIReferenceNodeManager UIReferenceNodeManager.java:109 returning icon for: \\ncc-ad-01\users\l.pickard\My Documents\KnowledgeManagementPapers\Alavi_Leidner_2001.pdf
2014-06-19 10:59:25,016 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 13 path: C:\Apps\Compendium\Skins\Default\reference.png
2014-06-19 10:59:25,016 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Apps\Compendium\Skins\Default\reference.png
2014-06-19 10:59:25,017 INFO  [AWT-EventQueue-0] c.c.u.UIReferenceNodeManager UIReferenceNodeManager.java:109 returning icon for: \\ncc-ad-01\users\l.pickard\My Documents\KnowledgeManagementPapers\Alavi_Leidner_2001.pdf
2014-06-19 10:59:25,017 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 4 path: C:\Apps\Compendium\Skins\Default\map_sm.png
2014-06-19 10:59:25,017 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Apps\Compendium\Skins\Default\map_sm.png
2014-06-19 10:59:25,044 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:231 loading icon id: 4 path: C:\Apps\Compendium\Skins\Default\map_sm.png
2014-06-19 10:59:25,045 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Apps\Compendium\Skins\Default\map_sm.png
2014-06-19 10:59:41,967 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:427 dnd drop detected: java.awt.dnd.DropTargetContext$TransferableProxy@14ba90f at location x=197, y=521
2014-06-19 10:59:41,981 ERROR [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:448 Exception...
java.awt.datatransfer.UnsupportedFlavorException: Unicode String
    at sun.awt.dnd.SunDropTargetContextPeer.getTransferData(Unknown Source) [na:1.7.0_60]
    at sun.awt.datatransfer.TransferableProxy.getTransferData(Unknown Source) ~[na:1.7.0_60]
    at java.awt.dnd.DropTargetContext$TransferableProxy.getTransferData(Unknown Source) ~[na:1.7.0_60]
    at com.compendium.ui.UIViewPane.onDrop_FileList(UIViewPane.java:695) ~[CompendiumNG.jar:2.1.4-SNAPSHOT]
    at com.compendium.ui.UIViewPane.drop(UIViewPane.java:438) ~[CompendiumNG.jar:2.1.4-SNAPSHOT]
    at java.awt.dnd.DropTarget.drop(Unknown Source) [na:1.7.0_60]
    at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source) [na:1.7.0_60]
    at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source) [na:1.7.0_60]
    at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source) [na:1.7.0_60]
    at sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source) [na:1.7.0_60]
    at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.7.0_60]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_60]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_60]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na:1.7.0_60]
    at java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source) [na:1.7.0_60]
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.7.0_60]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_60]
    at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.7.0_60]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_60]
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.7.0_60]
    at java.awt.EventQueue.access$200(Unknown Source) [na:1.7.0_60]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_60]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_60]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_60]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_60]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_60]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_60]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_60]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_60]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_60]
    at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.7.0_60]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.7.0_60]
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.7.0_60]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.7.0_60]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_60]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_60]
    at java.awt.EventDispatchThread.run(Unknown Source) [na:1.7.0_60]
</pre>

**Comment by maiklos** [comment]
thanks for the logfile. This will suffice.

**Comment by maiklos** [comment]
I think, I have managed to fix the issue. Could you please test it ?
You can download the latest dev. version from cloudbees. See here for details: http://www.compendiumng.org/download-cutting-edge/

fix provided in commit: 5389745b962ea27333e8846ba050648bddf50b29

**Comment by laurarhian** [comment]
I just had this version put on my work machine- problem solved!

Many thanks.

**Comment by maiklos** [comment]
you're welcome
if only more bugs were so easy to solve ;-)
