### ISSUE TITLE
NullPointerException when attempting to make a backup

### ISSUE THREAD

**Issue by davegomboc** [CompendiumNG/CompendiumNG#229]
Machine is amd64 Debian Jessie.  Java is Oracle 8.  The application was compiled from SHA a224577201d7ad0788e9737015a84221e12d7f19 (current 2.1.3) and installed locally.

Here's what is left on the console:

<pre>
2014-07-17 18:08:58,108 DEBUG [AWT-EventQueue-0]  o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: /home/dgomboc/CompendiumNG/Skins/Default/position.png
2014-07-17 18:08:58,108 DEBUG [AWT-EventQueue-0]  c.c.ui.UIImages UIImages.java:231 loading icon id: 7 path: /home/dgomboc/CompendiumNG/Skins/Default/issue.png
2014-07-17 18:08:58,108 DEBUG [AWT-EventQueue-0]  o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: /home/dgomboc/CompendiumNG/Skins/Default/issue.png
2014-07-17 18:08:58,108 DEBUG [AWT-EventQueue-0]  c.c.ui.UIImages UIImages.java:231 loading icon id: 7 path: /home/dgomboc/CompendiumNG/Skins/Default/issue.png
2014-07-17 18:08:58,109 DEBUG [AWT-EventQueue-0]  o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: /home/dgomboc/CompendiumNG/Skins/Default/issue.png
2014-07-17 18:08:58,109 DEBUG [AWT-EventQueue-0]  c.c.ui.UIImages UIImages.java:231 loading icon id: 9 path: /home/dgomboc/CompendiumNG/Skins/Default/argument.png
2014-07-17 18:08:58,109 DEBUG [AWT-EventQueue-0]  o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: /home/dgomboc/CompendiumNG/Skins/Default/argument.png
2014-07-17 18:11:47,706 DEBUG [AWT-EventQueue-0]  c.c.c.d.m.DBAdminDerbyDatabase DBAdminDatabase.java:398 checkVersion returning: 2.0.1
2014-07-17 18:12:08,937 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExamplePDF.pdf
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Java.java
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-XML.xml
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-PowerPoint.ppt
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Word.doc
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Excel.xls
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Access.mdb
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-readme.txt
2014-07-17 18:12:08,938 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-movie.mov
Exception in thread "UIDatabaseManagementDialog.actionPerformed-Backup" java.lang.NullPointerException
        at com.compendium.core.db.management.DBBackupDatabase.addStencilsToResources(DBBackupDatabase.java:421)
        at com.compendium.core.db.management.DBBackupDatabase.backupDatabaseToZip(DBBackupDatabase.java:277)
        at com.compendium.ui.dialogs.UIDatabaseManagementDialog$5.run(UIDatabaseManagementDialog.java:855)
</pre>

**Comment by maiklos** [comment]
I've tried to fix this problem in v 2.1.5 06a1c66c4cfacfe46cda8a738d07e6c857e88219.
Could you please retest on you platform ?

**Comment by davegomboc** [comment]
I'm now running d15d9d96bc41767d33ae5d4d121b0701915a4cd4  (current 2.1.5 tip).  When attempting a zip backup, the prior NPE no longer occurs, but other errors are now reported on the console:

<pre>
2014-07-21 04:08:46,168 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExamplePDF.pdf
2014-07-21 04:08:46,168 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Java.java
2014-07-21 04:08:46,168 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-XML.xml
2014-07-21 04:08:46,168 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-PowerPoint.ppt
2014-07-21 04:08:46,169 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Word.doc
2014-07-21 04:08:46,169 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Excel.xls
2014-07-21 04:08:46,169 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-Access.mdb
2014-07-21 04:08:46,169 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-readme.txt
2014-07-21 04:08:46,169 ERROR [UIDatabaseManagementDialog.actionPerformed-Backup]  c.c.c.d.m.DBBackupDatabase DBBackupDatabase.java:1083 NOT FOUND ON EXPORT: RefExample-movie.mov
</pre>

**Comment by maiklos** [comment]
this is because there is a file referenced from a node but the file doesn't exist. 
During backup CompendiumNG is checking if referenced file exists and copies it into the backup if it does otherwise it will alert you in this way.

**Comment by davegomboc** [comment]
Okay, I can see from the "linked file browser" feature in the tools menu that some references to those files remain.  I'd like to eradicate all such references.  Double-clicking on the RefExample-Excel.xls entry gives me a pop-up indicating "REFERENCE: with a Excel file link".  I can double-click again and see the details of the node.

At this point, I would prefer to find and delete the entire node (which I am sure is not part of my work), but I could not identify a simple way to do so.  I also tried to simply remove the text "RefExample-Excel.xls" from the Ref: field, but then I receive "Error in 'UINodeEditPanel.onUpdate'\n\nnull" in the dialog box, for understandable reasons.

I guess that as a workaround I will need to try placing a zero-length file at every place where a resource that is referenced was previously deleted.  It'd still be nice to track down where these nodes that contain the references actually are so that i can delete them.

**Comment by maiklos** [comment]
provide feature to easily search and delete nodes or references that don't exist on filesystem.
move to FSP as a new feature request.
