### ISSUE TITLE
Derby Admin db unble to be opened/created

### ISSUE THREAD

**Issue by ghost** [CompendiumNG/CompendiumNG#259]
Just compiled CompendiumNG 2.1.5 for Windows 7 64-bit with JDK 1.8.0_45 and the JRE 1.8.0_45, too, using the current gradle. The build & installation worked, but then when i invoked Start Compendium, a message appears in a non-modal box called Database Creation Error and its content is "The local Derby Administration database was unable to be opened/created ... 'system.simpleinterface' doesn't map to an existing object."

The messages in the log around this one are:

<pre>
2015-06-05 21:37:46,718 DEBUG [main] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2015-06-05 21:37:46,726 ERROR [main] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:832 Exception...
java.util.NoSuchElementException: 'system.simpleInterface' doesn't map to an existing object
    at org.apache.commons.configuration.AbstractConfiguration.getBoolean(AbstractConfiguration.java:644) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.connectToServices(ProjectCompendiumFrame.java:816) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.init(ProjectCompendiumFrame.java:553) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.initialiseFrame(ProjectCompendiumFrame.java:489) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ProjectCompendium.<init>(ProjectCompendium.java:436) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ProjectCompendium.main(ProjectCompendium.java:366) [CompendiumNG.jar:2.1.5-SNAPSHOT]
2015-06-05 21:37:46,726 INFO  [main] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6074 Error:The local Derby Administration database was unable to be opened/created... 'system.simpleInterface' doesn't map to an existing object
Please contact Compendium support staff.
2015-06-05 21:41:27,102 DEBUG [main] c.c.c.d.m.DBConnectionManager DBConnectionManager.java:300 about to shutdonw DerbyDB with: jdbc:derby:;shutdown=true
2015-06-05 21:41:27,456 ERROR [main] c.c.c.d.m.DBConnectionManager DBConnectionManager.java:304 Unable to shutdown Derby: 
java.sql.SQLException: Derby system shutdown.
</pre>

What am I doing wrong? Thank you in advance.

**Comment by maiklos** [comment]
could you please clarify which branch/commit (hash?) did you compile ?

**Comment by maiklos** [comment]
I don't have windows around me now, but could you tell if <b>compendiumng_config</b> is created in you home directory ? Does it contain <b>main.properties</b> file ?
Are there following lines in the main.properties file ?

<pre>
system.simpleInterface.info=The interface mode to start Compendium with when first installed. 'true' = simplified interface; 'false' = full interface. The user can override this and their choice is stored in Format.properties
system.simpleInterface=false
</pre>

Could it be that you compiled CompendiumNG but you didn't install it ?

could you please clarify which branch/commit (hash?) did you compile ?

**Comment by ghost** [comment]
Thank you VERY much! The main.properties file in compendium_config is empty, its file length is 0 bytes.
I did compile Compendium and then i did invoke the install.
Here is the commit: https://github.com/CompendiumNG/CompendiumNG/commit/14fc25dc0ed78d0264a32410006c7512338b2eb1. Is that what you sought for 2.1.5?

Best regards. -- Stan

**Comment by maiklos** [comment]
directory compendiumng_config (note: compendium<b>ng</b>) is created when it doesn't exist on the first run. If it existed (from whatever reason) and the files in it are corrupted (i.e. empty) then the result could be what is happening in your situation. 

While I have no idea why the file is empty (crash of compendiumng ?) I would suggest to delete or rename compendiumng_config directory and try to run ComendiumNG again. 

If the situation is the same (empty main.properties) I would guess that CompendiumNG has a problem to write to your home directory

**Comment by ghost** [comment]
Thank you. Do you think there is a problem because i am using Java DK 8 and not Java 7?  I ask because I am considering starting all over again, but do not want to proceed if the root problem is a poor choice of JDKs.  I appreciate your inputs.

**Comment by maiklos** [comment]
I can't imagine how it could be caused by jdk8

**Comment by ghost** [comment]
Good news! I tried everything all over again and, voila, it worked! Thank you so much for your collective guidance.
