### ISSUE TITLE
View marked dirty when switching between MySQL projects 

### ISSUE THREAD

**Issue by nmottagh** [CompendiumNG/CompendiumNG#269]
I am using the cutting edge (2.1.5) version with MySQL. I am unable to switch between projects. The flow is as follows:
Two projects exists, call them p1 and p2. 
- Both reside on the same MySQL host. 
- Both have the same login username/password. 
- p2 was "Exported as new" using a back up from p1; however, it also includes some new Nodes created after the export. 

1) Launch CompendiumNG.
2) Open project p1. Project p1 is launched successfully.
3) Close project p1. 
4) Open project p2. At this point, the UI shows objects from p1. 
5) Attempt to interact with the Nodes shown in the UI (from p1). Get an exception: 2016-05-11 17:29:48,227 INFO  [AWT-EventQueue-0] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6065 Error:Exception: (ProjectCompendiumFrame.addViewToDesktop-1)
Cannot initialize View 
null

Contents of the log file captured after step 4:

2016-05-11 17:29:44,074 ERROR [AWT-EventQueue-0] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6388 Exception...
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`ci_2016_q2_v2_1462763981535`.`ViewProperty`, CONSTRAINT `FK_ViewProperty_2` FOREIGN KEY (`ViewID`) REFERENCES `Node` (`NodeID`) ON DELETE CASCADE)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_45]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_45]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_45]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_45]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2818) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2157) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2460) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2377) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2361) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.db.DBViewProperty.insert(DBViewProperty.java:114) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.services.ViewPropertyService.createViewProperty(ViewPropertyService.java:89) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.saveViewProperties(ProjectCompendiumFrame.java:6385) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIViewFrame.internalFrameClosing(UIViewFrame.java:472) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at javax.swing.JInternalFrame.fireInternalFrameEvent(Unknown Source) [na:1.7.0_45]
    at javax.swing.JInternalFrame.doDefaultCloseAction(Unknown Source) [na:1.7.0_45]
    at javax.swing.plaf.basic.BasicInternalFrameTitlePane$CloseAction.actionPerformed(Unknown Source) [na:1.7.0_45]
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.7.0_45]
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [na:1.7.0_45]
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [na:1.7.0_45]
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.7.0_45]
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [na:1.7.0_45]
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.processMouseEvent(Unknown Source) [na:1.7.0_45]
    at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.processEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.processEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.access$200(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_45]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_45]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.run(Unknown Source) [na:1.7.0_45]
2016-05-11 17:29:44,469 WARN  [Timer-2] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:2343 Exception...
java.lang.NullPointerException: null
    at com.compendium.core.datamodel.View.isViewDirty(View.java:628) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.checkProjectDirty(ProjectCompendiumFrame.java:2336) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIRefreshManager$RefreshCache.run(UIRefreshManager.java:130) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at java.util.TimerThread.mainLoop(Unknown Source) [na:1.7.0_45]
    at java.util.TimerThread.run(Unknown Source) [na:1.7.0_45]
2016-05-11 17:29:44,470 WARN  [Timer-2] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:2343 Exception...
java.lang.NullPointerException: null
    at com.compendium.core.datamodel.View.isViewDirty(View.java:628) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.checkProjectDirty(ProjectCompendiumFrame.java:2336) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIRefreshManager$RefreshCache.run(UIRefreshManager.java:130) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at java.util.TimerThread.mainLoop(Unknown Source) [na:1.7.0_45]
    at java.util.TimerThread.run(Unknown Source) [na:1.7.0_45]
2016-05-11 17:29:44,470 INFO  [Timer-2] c.c.c.d.m.DBConnectionManager DBConnectionManager.java:393 connection to database (URL=jdbc:mysql://wcdynamo4.torolab.ibm.com/ci_2016_q2_v2_1462763981535)
2016-05-11 17:29:44,470 INFO  [Timer-2] c.c.c.d.m.DBConnectionManager DBConnectionManager.java:412 connection url =jdbc:mysql://wcdynamo4.torolab.ibm.com/ci_2016_q2_v2_1462763981535
2016-05-11 17:29:45,261 ERROR [AWT-EventQueue-0] c.c.ui.plaf.NodeUI NodeUI.java:2329 Exception...
2016-05-11 17:29:46,379 ERROR [AWT-EventQueue-0] c.c.ui.plaf.NodeUI NodeUI.java:2349 Exception...
java.lang.NullPointerException: null
    at com.compendium.core.datamodel.View.setNodePosition(View.java:1576) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.NodeUI.mouseReleased(NodeUI.java:2346) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.processMouseEvent(Unknown Source) [na:1.7.0_45]
    at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.processEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.processEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.access$200(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_45]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_45]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.run(Unknown Source) [na:1.7.0_45]
2016-05-11 17:29:47,671 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:217 loading icon id: 3 path: C:\CompendiumNG\Skins\Default\list_sm.png
2016-05-11 17:29:47,672 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:156 ImageIconCache hit on: C:\CompendiumNG\Skins\Default\list_sm.png
2016-05-11 17:29:48,226 ERROR [AWT-EventQueue-0] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:5668 Exception...
java.lang.NullPointerException: null
    at com.compendium.core.datamodel.View.initializeMembers(View.java:581) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:5665) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:5602) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.NodeUI.openNode(NodeUI.java:2226) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.NodeUI.keyPressed(NodeUI.java:4174) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at java.awt.Component.processKeyEvent(Unknown Source) [na:1.7.0_45]
    at javax.swing.JComponent.processKeyEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.processEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.processEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source) [na:1.7.0_45]
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.Component.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.access$200(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_45]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue$4.run(Unknown Source) [na:1.7.0_45]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_45]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_45]
    at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_45]
    at java.awt.EventDispatchThread.run(Unknown Source) [na:1.7.0_45]
2016-05-11 17:29:48,227 INFO  [AWT-EventQueue-0] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6065 Error:Exception: (ProjectCompendiumFrame.addViewToDesktop-1)
Cannot initialize View 
null
2016-05-11 17:29:54,470 WARN  [Timer-2] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:2343 Exception...
java.lang.NullPointerException: null
    at com.compendium.core.datamodel.View.isViewDirty(View.java:628) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.checkProjectDirty(ProjectCompendiumFrame.java:2336) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIRefreshManager$RefreshCache.run(UIRefreshManager.java:130) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at java.util.TimerThread.mainLoop(Unknown Source) [na:1.7.0_45]
    at java.util.TimerThread.run(Unknown Source) [na:1.7.0_45]
2016-05-11 17:29:54,471 WARN  [Timer-2] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:2343 Exception...
java.lang.NullPointerException: null
    at com.compendium.core.datamodel.View.isViewDirty(View.java:628) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.checkProjectDirty(ProjectCompendiumFrame.java:2336) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIRefreshManager$RefreshCache.run(UIRefreshManager.java:130) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at java.util.TimerThread.mainLoop(Unknown Source) [na:1.7.0_45]
    at java.util.TimerThread.run(Unknown Source) [na:1.7.0_45]

**Comment by nmottagh** [comment]
Cannot be reproduced in 2.1.4.
