### ISSUE TITLE
a NullPointerException at UIToolBarFormat.setNodeOrLinkSelected(UIToolBarFormat.java:1388)

### ISSUE THREAD

**Issue by asmexcaliburwoods** [CompendiumNG/CompendiumNG#275]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.compendium.ui.toolbars.UIToolBarFormat.setNodeOrLinkSelected(UIToolBarFormat.java:1388)
        at com.compendium.ui.toolbars.UIToolBarManager.setNodeOrLinkSelected(UIToolBarManager.java:923)
        at com.compendium.ui.ProjectCompendiumFrame.setNodeOrLinkSelected(ProjectCompendiumFrame.java:6410)
        at com.compendium.ui.UIViewPane.processSelectedNode(UIViewPane.java:2240)
        at com.compendium.ui.UIViewPane.setSelectedNode(UIViewPane.java:2215)
        at com.compendium.ui.plaf.NodeUI.mouseClicked(NodeUI.java:2194)
        at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
        at java.awt.Component.processMouseEvent(Component.java:6519)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.awt.EventQueue$4.run(EventQueue.java:718)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:218)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:133)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:122)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:118)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:110)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by asmexcaliburwoods** [comment]
CNG version from About box: 2.1.5
CNG was obtained from https://compendium-ng.ci.cloudbees.com/job/cng-gradle/lastSuccessfulBuild/artifact/application/build/CompendiumNG-installer.jar

**Comment by SebastianBoell** [comment]
You downloaded the latest 2.1.5 build. Could you also give some context on this and how to re-produce? E.g. what OS are you working.

**Comment by asmexcaliburwoods** [comment]
```
user@pc:~$ lsb_release -a ; uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Linux pc 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by asmexcaliburwoods** [comment]
How to reproduce: I don't know.
