### ISSUE TITLE
Moving between projects in one session get null error

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#67]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=959

plymouth25k@yahoo.com 2010-12-13 15:53:01 GMT

When I close a project and then go to a second project in the same session, the
second project will open and work fine. However, if I close the second project
and try to go back to the first project, the first project will open but will
hang with a null error when I try to perform an action on a node in the first
project.
I currently have three total projects set up in compendium (all one user same
passcode).

[reply] [-] Comment 1 Michelle Bachler 2010-12-16 09:25:31 GMT

I have verified that this is indeed a bug with Beta 1.
Something is not being initialised correctly it seems, from the details in the
log file.

Thank you for reporting this. 

Michelle

[reply] [-] Comment 2 Michelle Bachler 2010-12-16 10:16:09 GMT

**\* Issue 935 has been marked as a duplicate of this issue. ***

**Comment by SebastianBoell** [comment]
Can confirm this for M1. 

Also the right click menu dissapeared.
A map openes after an error message, but no content is displayed.

**Comment by SebastianBoell** [comment]
It seems that issue #67 here and issue #68 are due to the same bug.

**Comment by maiklos** [comment]
related stack trace when this happens:

 INFO [ProjectCompendiumFrame.onFileOpen](UIMapViewFrame.java:938) - viewframe not selected because null
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at com.compendium.ui.toolbars.UIToolBarFormat.setNodeOrLinkSelected(UIToolBarFormat.java:1418)
    at com.compendium.ui.toolbars.UIToolBarManager.setNodeOrLinkSelected(UIToolBarManager.java:916)
    at com.compendium.ui.ProjectCompendiumFrame.setNodeOrLinkSelected(ProjectCompendiumFrame.java:6623)
    at com.compendium.ui.UIViewPane.processSelectedNode(UIViewPane.java:2230)
    at com.compendium.ui.UIViewPane.setSelectedNode(UIViewPane.java:2205)
    at com.compendium.ui.plaf.NodeUI.mouseClicked(NodeUI.java:2270)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:253)
    at java.awt.Component.processMouseEvent(Component.java:6300)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6062)
    at java.awt.Container.processEvent(Container.java:2039)
    at java.awt.Component.dispatchEventImpl(Component.java:4660)
    at java.awt.Container.dispatchEventImpl(Container.java:2097)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4245)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
    at java.awt.Container.dispatchEventImpl(Container.java:2083)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:668)
    at java.awt.EventQueue.access$400(EventQueue.java:81)
    at java.awt.EventQueue$2.run(EventQueue.java:627)
    at java.awt.EventQueue$2.run(EventQueue.java:625)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:641)
    at java.awt.EventQueue$3.run(EventQueue.java:639)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:638)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at com.compendium.ui.toolbars.UIToolBarFormat.setNodeOrLinkSelected(UIToolBarFormat.java:1418)
    at com.compendium.ui.toolbars.UIToolBarManager.setNodeOrLinkSelected(UIToolBarManager.java:916)
    at com.compendium.ui.ProjectCompendiumFrame.setNodeOrLinkSelected(ProjectCompendiumFrame.java:6623)
    at com.compendium.ui.UIViewPane.processSelectedNode(UIViewPane.java:2230)
    at com.compendium.ui.UIViewPane.setSelectedNode(UIViewPane.java:2205)
    at com.compendium.ui.plaf.NodeUI.mouseClicked(NodeUI.java:2270)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:253)
    at java.awt.Component.processMouseEvent(Component.java:6300)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6062)
    at java.awt.Container.processEvent(Container.java:2039)
    at java.awt.Component.dispatchEventImpl(Component.java:4660)
    at java.awt.Container.dispatchEventImpl(Container.java:2097)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4245)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
    at java.awt.Container.dispatchEventImpl(Container.java:2083)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:668)
    at java.awt.EventQueue.access$400(EventQueue.java:81)
    at java.awt.EventQueue$2.run(EventQueue.java:627)
    at java.awt.EventQueue$2.run(EventQueue.java:625)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:641)
    at java.awt.EventQueue$3.run(EventQueue.java:639)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:638)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
ERROR [AWT-EventQueue-0](ProjectCompendiumFrame.java:5877) - Error...
java.lang.NullPointerException
    at com.compendium.core.datamodel.View.initializeMembers(View.java:598)
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:5874)
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:5811)
    at com.compendium.ui.plaf.NodeUI.openNode(NodeUI.java:2303)
    at com.compendium.ui.plaf.NodeUI.mouseClicked(NodeUI.java:2262)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:253)
    at java.awt.Component.processMouseEvent(Component.java:6300)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6062)
    at java.awt.Container.processEvent(Container.java:2039)
    at java.awt.Component.dispatchEventImpl(Component.java:4660)
    at java.awt.Container.dispatchEventImpl(Container.java:2097)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4245)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
    at java.awt.Container.dispatchEventImpl(Container.java:2083)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4488)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:668)
    at java.awt.EventQueue.access$400(EventQueue.java:81)
    at java.awt.EventQueue$2.run(EventQueue.java:627)
    at java.awt.EventQueue$2.run(EventQueue.java:625)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:641)
    at java.awt.EventQueue$3.run(EventQueue.java:639)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:638)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
 INFO [AWT-EventQueue-0](ProjectCompendiumFrame.java:6279) - Error:Exception: (ProjectCompendiumFrame.addViewToDesktop-1)
Cannot initialize View 
null
